# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spring-docker-service
spec:
  selector:
    app: spring-docker
  ports:
  - port: 8085
    targetPort: 8085
    name: p1
  - port: 8086
    targetPort: 8086
    name: p2
  type: LoadBalancer