apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-02-05T18:53:08Z"
  labels:
    run: spring-docker-pod
  name: spring-docker-pod
  namespace: a
  resourceVersion: "2984"
  selfLink: /api/v1/namespaces/a/pods/spring-docker-pod
  uid: daa92fd9-4a7b-4dd0-b8ee-3e29893d7f35
spec:
  containers:
  - image: spring-docker
    imagePullPolicy: Never
    name: spring-docker-pod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-48cjq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-48cjq
    secret:
      defaultMode: 420
      secretName: default-token-48cjq
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-02-05T18:53:09Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-02-05T18:53:09Z"
    message: 'containers with unready status: [spring-docker-pod]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-02-05T18:53:09Z"
    message: 'containers with unready status: [spring-docker-pod]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-02-05T18:53:08Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: spring-docker
    imageID: ""
    lastState: {}
    name: spring-docker-pod
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "spring-docker"
        reason: ImagePullBackOff
  hostIP: 192.168.65.3
  phase: Pending
  podIP: 10.1.0.7
  podIPs:
  - ip: 10.1.0.7
  qosClass: BestEffort
  startTime: "2021-02-05T18:53:09Z"